# Generated by Django 5.0.7 on 2024-08-05 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskpermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskpermission',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('update', 'Update')], max_length=10),
        ),
        migrations.AlterField(
            model_name='taskpermission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='todo.task'),
        ),
        migrations.AlterField(
            model_name='taskpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
